audit_header: false
title: Memphis Real Estate Video Blog with John Quinn
description: >-
  Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET --
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The -- CLIENT BRAND --, your
  professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: John Quinn
  title:
  license_number:
  about_markdown: >-
    The John Quinn Team specializes in matching buyers and sellers for over 30
    years. He represents the region's finest properties with exceptional skill
    using the most innovative technologies currently available. The John Quinn
    Team offers ultimate privacy and security, speed, and efficiency. His years
    of full-time experience have given him a clear understanding of the mindset
    of home buyers and sellers and a thorough understanding of the regional
    marketplace.
  market: Memphis
  brand: The John Quinn Home Selling Team
  brokerage: RE/MAX Experts
  address: 1930 Exeter Road<br>Germantown, TN 38138
  phone: 901-591-8100
  phone_type: Direct
  phone2: 901-685-6000
  phone2_type: Main
  email: john@johnquinnteam.com
  url: https://www.johnquinnteam.com
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.johnquinnrealestate.com/sellers/whats-my-home-worth/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.johnquinnrealestate.com/buyers/personalized-home-search/
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your -- MARKET -- Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: https://www.johnquinnrealestate.com/sellers/whats-my-home-worth/
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a -- MARKET -- Home?
    CTA_text2: Search the entire MLS for your -- MARKET -- home.
    CTA_link_text2: Search the MLS
    CTA_url2: http://www.johnquinnteam.com/communities/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com
socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/JohnQuinnRealEstate/
  linkedin_url:
  gplus_url: https://plus.google.com/110028377956433049718
  youtube_url: https://www.youtube.com/channel/UC4Y__LL3OaKHowsfOqDXitg
  twitter_url: https://twitter.com/JQSellingTeam
  instagram_url:
  pinterest_url: https://www.pinterest.com/johnquinnteam/
  zillow_url: https://www.zillow.com/profile/JohnQuinnRealtor/For-Sale-Listings/?my=y
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Real Estate Podcast with John Quinn
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: John Quinn
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 80
  hero_text: '-- MARKET -- Real Estate Video Blog'
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(0, 0, 0, 0.75)
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: rgba(0, 0, 0, 0)
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
